name: 'Codex Auto-Implement'
description: 'Automatically implement a GitHub issue using OpenAI Codex CLI and open a PR'

inputs:
  issue-number:
    description: 'GitHub issue number to implement'
    required: true
  repo-token:
    description: 'GitHub token with contents, issues, and pull-requests write permissions'
    required: true
  base-branch:
    description: 'Base branch to create the feature branch from'
    required: false
    default: 'main'
  extra-prompt:
    description: 'Additional instructions appended to the Codex prompt'
    required: false
    default: ''
  pr-labels:
    description: 'Comma-separated labels to apply to the created PR (missing labels are auto-created)'
    required: false
    default: 'codex-generated'
  timeout-minutes:
    description: 'Timeout in minutes for the Codex execution'
    required: false
    default: '30'
  factory-api-url:
    description: 'Factory backend base URL (e.g. https://factory.silver-key.nl)'
    required: false
    default: ''
  factory-api-token:
    description: 'Shared token for posting run updates to Factory backend'
    required: false
    default: ''
  factory-run-id:
    description: 'Optional run ID override for Factory backend tracking'
    required: false
    default: ''
  factory-ticket-id:
    description: 'Optional Factory ticket ID to link the run to'
    required: false
    default: ''

outputs:
  pr-number:
    description: 'The created pull request number'
    value: ${{ steps.implement.outputs.pr-number }}
  pr-url:
    description: 'The created pull request URL'
    value: ${{ steps.implement.outputs.pr-url }}

runs:
  using: 'composite'
  steps:
    - name: Announce run start to Factory
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.repo-token }}
        GITHUB_TOKEN: ${{ inputs.repo-token }}
        ISSUE_NUMBER: ${{ inputs.issue-number }}
        BASE_BRANCH: ${{ inputs.base-branch }}
        EXTRA_PROMPT: ${{ inputs.extra-prompt }}
        PR_LABELS: ${{ inputs.pr-labels }}
        TIMEOUT_MINUTES: ${{ inputs.timeout-minutes }}
        FACTORY_API_URL: ${{ inputs.factory-api-url }}
        FACTORY_API_TOKEN: ${{ inputs.factory-api-token }}
        FACTORY_RUN_ID: ${{ inputs.factory-run-id }}
        FACTORY_TICKET_ID: ${{ inputs.factory-ticket-id }}
        ACTION_PATH: ${{ github.action_path }}
      run: |
        chmod +x "$ACTION_PATH/scripts/announce-start.sh"
        "$ACTION_PATH/scripts/announce-start.sh"

    - name: Research
      id: research
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.repo-token }}
        GITHUB_TOKEN: ${{ inputs.repo-token }}
        ISSUE_NUMBER: ${{ inputs.issue-number }}
        BASE_BRANCH: ${{ inputs.base-branch }}
        EXTRA_PROMPT: ${{ inputs.extra-prompt }}
        PR_LABELS: ${{ inputs.pr-labels }}
        TIMEOUT_MINUTES: ${{ inputs.timeout-minutes }}
        FACTORY_API_URL: ${{ inputs.factory-api-url }}
        FACTORY_API_TOKEN: ${{ inputs.factory-api-token }}
        FACTORY_RUN_ID: ${{ inputs.factory-run-id }}
        FACTORY_TICKET_ID: ${{ inputs.factory-ticket-id }}
        ACTION_PATH: ${{ github.action_path }}
      run: |
        chmod +x "$ACTION_PATH/scripts/implement-issue.sh" \
          "$ACTION_PATH/scripts/research.sh"
        "$ACTION_PATH/scripts/research.sh"

    - name: Plan
      id: plan
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.repo-token }}
        GITHUB_TOKEN: ${{ inputs.repo-token }}
        ISSUE_NUMBER: ${{ inputs.issue-number }}
        BASE_BRANCH: ${{ inputs.base-branch }}
        EXTRA_PROMPT: ${{ inputs.extra-prompt }}
        PR_LABELS: ${{ inputs.pr-labels }}
        TIMEOUT_MINUTES: ${{ inputs.timeout-minutes }}
        FACTORY_API_URL: ${{ inputs.factory-api-url }}
        FACTORY_API_TOKEN: ${{ inputs.factory-api-token }}
        FACTORY_RUN_ID: ${{ inputs.factory-run-id }}
        FACTORY_TICKET_ID: ${{ inputs.factory-ticket-id }}
        ACTION_PATH: ${{ github.action_path }}
      run: |
        chmod +x "$ACTION_PATH/scripts/implement-issue.sh" \
          "$ACTION_PATH/scripts/plan.sh"
        "$ACTION_PATH/scripts/plan.sh"

    - name: Implement
      id: implement
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.repo-token }}
        GITHUB_TOKEN: ${{ inputs.repo-token }}
        ISSUE_NUMBER: ${{ inputs.issue-number }}
        BASE_BRANCH: ${{ inputs.base-branch }}
        EXTRA_PROMPT: ${{ inputs.extra-prompt }}
        PR_LABELS: ${{ inputs.pr-labels }}
        TIMEOUT_MINUTES: ${{ inputs.timeout-minutes }}
        FACTORY_API_URL: ${{ inputs.factory-api-url }}
        FACTORY_API_TOKEN: ${{ inputs.factory-api-token }}
        FACTORY_RUN_ID: ${{ inputs.factory-run-id }}
        FACTORY_TICKET_ID: ${{ inputs.factory-ticket-id }}
        ACTION_PATH: ${{ github.action_path }}
      run: |
        chmod +x "$ACTION_PATH/scripts/implement-issue.sh" \
          "$ACTION_PATH/scripts/implement.sh"
        "$ACTION_PATH/scripts/implement.sh"

    - name: Review
      id: review
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.repo-token }}
        GITHUB_TOKEN: ${{ inputs.repo-token }}
        ISSUE_NUMBER: ${{ inputs.issue-number }}
        BASE_BRANCH: ${{ inputs.base-branch }}
        EXTRA_PROMPT: ${{ inputs.extra-prompt }}
        PR_LABELS: ${{ inputs.pr-labels }}
        TIMEOUT_MINUTES: ${{ inputs.timeout-minutes }}
        FACTORY_API_URL: ${{ inputs.factory-api-url }}
        FACTORY_API_TOKEN: ${{ inputs.factory-api-token }}
        FACTORY_RUN_ID: ${{ inputs.factory-run-id }}
        FACTORY_TICKET_ID: ${{ inputs.factory-ticket-id }}
        ACTION_PATH: ${{ github.action_path }}
      run: |
        chmod +x "$ACTION_PATH/scripts/implement-issue.sh" \
          "$ACTION_PATH/scripts/review.sh"
        "$ACTION_PATH/scripts/review.sh"
